# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DEMStyleAll
                                 A QGIS plugin
 DEMスタイル一括設定
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-26
        copyright            :
        email                :

        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import sys
from pathlib import Path


plugin_root = str(Path(__file__).resolve().parent)
if plugin_root not in sys.path:
    sys.path.insert(0, plugin_root)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DEMStyleAll class from file DEMStyleAll.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .demstyle_all import DEMStyleAll

    return DEMStyleAll(iface)
