# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DEMStyleAllDialog
                                 A QGIS plugin
 DEMスタイル一括設定
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-26
        git sha              : $Format:%H$
        copyright            :
        email                :

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from __future__ import annotations

import os
from typing import override

from qgis.PyQt.QtCore import Qt
from qgis.core import QgsPointXY
from qgis.core import QgsRaster
from qgis.core import QgsMapLayerType
from qgis.core import QgsRasterLayer
from qgis.gui import QgsMapTool
from qgis.gui import QgsMapToolEmitPoint
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from .settings import DialogSettings

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "demstyle_all_dialog_base.ui")
)

DATA_RANGE_VALUES = [5, 10, 20, 50, 100, 200]


class DEMStyleAllDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface):
        """Constructor."""
        super(DEMStyleAllDialog, self).__init__(parent=None)
        self.iface = iface
        self.settings = DialogSettings()
        self.setupUi(self)

        self.canvas = self.iface.mapCanvas()
        self.map_tool = QgsMapToolEmitPoint(self.canvas)

        # 初回起動時のデータレンジ値設定
        self.dataRangeSlider.setValue(2)
        self.dataRangeLineEdit.setText(str(DATA_RANGE_VALUES[2]))

        self.settings.restore_dialog_state(self)  # ダイアログ設定を復元

        # シグナル接続
        self.dataRangeSlider.valueChanged.connect(self.handle_slider_change)
        self.setElevationButton.clicked.connect(self.start_capture_mode)
        self.map_tool.canvasClicked.connect(self.handle_get_elevation)

        # ダイアログ表示時にOKボタンへフォーカスを設定
        ok_button = self.dialogButtonBox.button(QtWidgets.QDialogButtonBox.Ok)
        if ok_button:
            ok_button.setFocus()

    def handle_slider_change(self, index):
        """スライダーの値（インデックス）変更時の処理"""
        try:
            # リストから実数値を取得
            actual_value = DATA_RANGE_VALUES[index]
            # LineEditに文字列として反映
            self.dataRangeLineEdit.setText(str(actual_value))
        except IndexError:
            pass

    def get_current_data_range(self):
        """現在のデータレンジを取得する"""
        index = self.dataRangeSlider.value()
        return self.data_values[index]

    def start_capture_mode(self):
        """地図キャンバス上の標高をマウスクリックで取得するモード"""
        self.canvas.setMapTool(self.map_tool)

    def handle_get_elevation(self, point, button):
        """標高を取得後の処理"""
        self.canvas.unsetMapTool(self.map_tool)  # ツールを解除

        # 標高取得後にダイアログを最前面に表示
        self.raise_()
        self.activateWindow()

        # アクティブな地物レイヤを取得
        try:
            layer = get_active_raster_layer(self.iface)
        except Exception:
            message = "地物レイヤを選択してください"
            self.iface.messageBar().pushMessage("エラー", message, level=1)
            return

        # クリック地点の標高値を取得
        res = layer.dataProvider().identify(point, QgsRaster.IdentifyFormatValue)

        if not res.isValid():
            message = "標高値の取得に失敗しました (0)"
            QtWidgets.QMessageBox.warning(self, "エラー", message)
            return

        # 結果は辞書形式 {バンド番号: 値} で返される (通常、DEMは第1バンド)
        results = res.results()
        elevation = results.get(1)  # バンド1の値を取得

        if elevation is None:
            message = "標高値の取得に失敗しました (1)"
            QtWidgets.QMessageBox.warning(self, "エラー", message)
            return

        rounded_elevation = int(round(elevation / 5) * 5)  # 標高地の値を丸め

        # スピンボックスに値をセット
        self.midElevationSpinBox.setValue(rounded_elevation)

    @override
    def closeEvent(self, event):
        """ウィンドウを閉じる前に設定を保存"""
        self.settings.save_dialog_state(self)
        event.accept()


def get_active_raster_layer(iface) -> QgsRasterLayer:
    """選択中の地物レイヤを取得"""
    layer = iface.activeLayer()  # 選択中のレイヤを取得
    assert layer is not None
    assert layer.type() == QgsMapLayerType.RasterLayer
    return layer
